name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run : npm i --ignore-scripts
    - run : npm run prepare
    - name: Update version from tag
      run: |
        TAG_VERSION=${GITHUB_REF#refs/tags/}
        npm version $TAG_VERSION --no-git-tag-version
    - name: Publish to npm
      run : |
        npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
        npm publish --ignore-scripts --access=public
      env :
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}